#!/bin/sh
# xprofile
# Specify startup programs here to make them independent of the desktop
# environment or window manager

# Set keyboard rate
xset r rate 200 60

# Merge xresources
xrdb -merge ~/.config/X11/xresources 

# Start compositor
picom &

# Activate NumLock key
numlockx on

# Execute custom script to follow playerctl updates
playerctl-follow &

# Set wallpaper
xwallpaper --zoom $HOME/Pictures/current-wallpaper

# Start the polkit agent to allow GUI editors to modify system-wide config files
# polkit-dumb-agent &

# Start unclutter to automatically hide the cursor
unclutter &

# Time/date embedded into the bare DWM status bar
while true; do
   xsetroot -name "$(date) "
   sleep 1
done &
